inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Max: 130
  Exclude:
    - 'lib/browse_everything/driver/google_drive.rb'
    - 'lib/browse_everything/provider/google_drive.rb'
Layout/LineLength:
  Max: 400
  Exclude:
    - 'spec/lib/browse_everything/driver/box_spec.rb'
    - 'spec/lib/browse_everything/driver/dropbox_spec.rb'
Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
    - 'swagger/spec/**/*'

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/**/*'
    
RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'swagger/spec/integration/authorizations_spec.rb'
    - 'swagger/spec/integration/bytestreams_spec.rb'
    - 'swagger/spec/integration/containers_spec.rb'
    - 'swagger/spec/integration/providers_spec.rb'
    - 'swagger/spec/integration/sessions_spec.rb'
    - 'swagger/spec/integration/uploads_spec.rb'
    - 'spec/controllers/browse_everything/sessions_controller_spec.rb'

Style/NumericLiterals:
  MinDigits: 7

Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Naming/FileName:
  Exclude:
    - 'browse-everything.gemspec'
    - 'Gemfile'
    - 'lib/browse-everything.rb'

Style/MixinUsage:
  Exclude:
    - 'spec/lib/browse_everything/driver/s3_spec.rb'
    - 'spec/lib/browse_everything/driver/google_drive_spec.rb'
    - 'spec/lib/browse_everything/driver/file_system_spec.rb'
    - 'spec/lib/browse_everything/driver/dropbox_spec.rb'
    - 'spec/lib/browse_everything/driver/box_spec.rb'
    - 'spec/lib/browse_everything/driver/base_spec.rb'
    - 'spec/lib/browse_everything/browser_spec.rb'
    - 'spec/services/browser_factory_spec.rb'
    - 'spec/helper/browse_everything_controller_helper_spec.rb'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'
