inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Max: 130

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 400

RSpec/NestedGroups:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/unit/google_drive_spec.rb'
    - 'spec/features/select_files_spec.rb'
    - 'spec/javascripts/jasmine_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/unit/google_drive_spec.rb'

RSpec/LeadingSubject:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/IndentationConsistency:
  EnforcedStyle: rails
