language: ruby
# Workaround for https://github.com/travis-ci/travis-ci/issues/8836
# sudo: false
sudo: required
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  bundler: true

before_install:
  - gem update --system # https://docs.travis-ci.com/user/languages/ruby/#Upgrading-RubyGems
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

rvm:
  - 2.4.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.1.4"
    - "RAILS_VERSION=5.0.6"
